[main]
identifier = 'dev'
# number_of_processors = 2

[restraints]
A = [933, 934, 937, 938, 946, 950]
B = [6, 8, 44, 45, 46, 47, 48, 49, 68, 70]

[molecules]
A = "2OOB_r_u.pdb"
B = "2OOB_l_u.pdb"
# native = "2OOB_native.pdb"

# If these are not defined, then they'll be taken from etc/ga_params.toml
#======================================================================#
[ga]
population_size = 10
max_number_of_generations = 100
crossover_probability = 0.2
mutation_probability = 0.8

[analysis]
contact_cutoff = 5.0
clust_cutoff = 0.75
clust_min_size = 4
clust_n = 1000
#======================================================================#
