[main]
identifier = 'dev'
number_of_processors = 4

[ga]
population_size = 10
max_number_of_generations = 10

[restraints]
A = [933, 934, 937, 938, 946, 950]
B = [6, 8, 44, 45, 46, 47, 48, 49, 68, 70]

[molecules]
A = '2OOB_r_u.pdb'
B = '2OOB_l_u.pdb'
native = '2OOB_native.pdb'
