name: gdock
channels:
  - defaults
dependencies:
  - python=3.6.12
  - pip=20.2.3
  - biopython=1.78
  - numpy=1.19.1
  - scipy=1.5.2
  - toml=0.10.1
  - pip:
    - deap==1.3.1
    - pdb-tools==2.2.1
    - pyquaternion==0.9.9
    - codecov==2.1.10
    - coverage==5.3
